# Generated by Django 3.1 on 2021-09-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the publisher.', max_length=50)),
                ('website', models.URLField(help_text="The publisher's website.")),
                ('email', models.EmailField(help_text="The publisher's e-mail address.", max_length=254)),
            ],
        ),
    ]
